### ISSUE TITLE
Your Demo

### ISSUE THREAD

**Issue by ghost** [straaljager/GPU-path-tracing-tutorial-4#6]
Demo App runs fine, 

Under which license is your code?
Some header files contain the NVIDIA license, so that code can be used commercially; what about the other files?

However, the demo does not close the console window on app exit after closing the render window; tested on Win10 Pro 64bit v1809.

**Comment by straaljager** [comment]
Hi, licence is Apache 2.0, same as the one that the Nvidia ray tracing framework it's based on uses.

I haven't tested on Win 10/10 Pro, but thanks for letting me know.

**Comment by ghost** [comment]
Thanks
